version: '3.8'

services:
  app:
    build:
      context: ./task-backend
      dockerfile: Dockerfile  # Path to the Dockerfile
    container_name: lumen_app
    restart: always
    ports:
      - "8330:8330" 
      - "8331:8331" 
    volumes:
      - ./task-backend:/var/www  # Bind the task-backend folder to the container
      - /var/www/vendor

    depends_on:
      - db
    environment:
      APP_ENV: local
      APP_DEBUG: true
      APP_URL: http://localhost
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: taskmanager  
      DB_USERNAME: taskmanager     
      DB_PASSWORD: taskmanager  
      JWT_SECRET: e5qmgYAsFLAH3rFHEL2YWtN427xGkUffSTrX1CCtN8Mzgav0WF2J09NwuXnI46Fm
    command: >
        sh -c "
          until nc -z db 3306; do
            echo 'Waiting for MySQL...';
            sleep 1;
          done;
          if ! php artisan migrate:status | grep -q 'Ran?'; then
            php artisan migrate;
          fi;
          supervisord -c supervisord.conf;
        "

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: taskmanager  
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: taskmanager
      MYSQL_PASSWORD: taskmanager
    ports:
      - "8332:3306"
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - ./database/mysql-data:/var/lib/mysql:rw

    
  frontend:
    build:
      context: ./task-frontend/
      dockerfile: Dockerfile
      args:
          VITE_API_URL: "${VITE_API_URL:-http://127.0.0.1:8330}"
          VITE_WEB_SOCKET_URL: "${VITE_WEB_SOCKET_URL:-ws://127.0.0.1:8331}"
    container_name: frontend_app
    restart: always
    ports:
      - "8333:80"  
    depends_on:
      - app  # Ensure backend is up before frontend

volumes:
  mysql-data:


